---
- name: Installing and Launch MetricBeat
  hosts: webservers
  become: yes
  tasks:
   
   # Use command module
  - name: Download metricbeat .deb file
    command: curl -L -O curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
   
   # Use command module
  - name: Install metricbeat .deb
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb
    
  # Use copy module
  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml
    
   # Use command module
  - name: Enable and Configure System Module
    command: sudo metricbeat modules enable docker
   
    # Use command module
  - name: Setup metricbeat
    command: sudo metricbeat setup
    
   # Use command module
  - name: Start metricbeat service
    command: sudo service metricbeat start

  - name: enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes